name: build site

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.7'

    - name: Install MkDocs
      run: |
        sudo pip install pip --upgrade
        sudo pip install 'mkdocs==1.1'
      
    - name: Build site
      run: |
        cd mkdocs
        mkdocs build -d ../docs

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'JonathanRob@users.noreply.github.com'
        git commit -am "Build site"
        git push
